# Bot token
token=""

# Path to server.jar 
server_jar = ""

# Your discord server ID and logging channel ID 
discord_guild = 
logging_channel = 

# Set your heap limits, usually I'd do 6G or 8G for both of them, depending on mods and player count.
max_heap_size = ""
min_heap_size = ""
